version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.29
    restart: always
    ports: 
    - "4466:4466"
    environment:
      PRISMA_CONFIG: | 
        port: 4466
        managementApiSecret: fpem12
        databases:
          default:
            connector: mongo
            uri: >-
              mongodb+srv://lunatk:gkdl28$$*@cluster0-3ski0.gcp.mongodb.net/test?retryWrites=true
